org: informotive
app: reminder-app
service: Reminder-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.14
  region: us-east-1
  environment: 
    REMINDERS_TABLE: Reminders
    SENDER_EMAIL_ID: kthummar786@gmail.com
  iam:
    role:
      name: reminder-app
      path: /reminder-app/
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'

functions:
  ReminderCreate:
    handler: createReminder.lambda_handler
    layers: 
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:boto3-stubs-dynamodb-ses_1_42_62:1
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:aws-lambda-powertools-3_24_0:1
    events:
      - http:
          path: /reminders
          method: POST

  ReminderNotification:
    handler: reminderNotification.reminder_notification
    layers:
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:boto3-stubs-dynamodb-ses_1_42_62:1
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:aws-lambda-powertools-3_24_0:1
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - RemindersTable
              - StreamArn

resources:

  Resources:

    RemindersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REMINDERS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: reminderId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: reminderId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: reminderAt
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES