org: informotive
app: reminder-app
service: my-service
service: Reminder-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.14

functions:
  hello:
    handler: createReminder.create_reminder
